name: syn_logger_console_writer
description: Service dependency for the synaptic_thread_safe_logger, required to write logs to the console
version: 1.0.1
repository: https://github.com/synaptik-develop/syn_logger_console_writer

environment:
  sdk: ^3.7.2

dependencies:
  stack_trace: ^1.12.1
  syn_log_interface: ^1.0.2

dev_dependencies:
  dart_code_linter: ^1.3.0
  dartdoc: ^6.3.0
  lint: ^2.3.0
